spring:
  application:
    name: reagentes-api

  datasource:
    url: jdbc:postgresql://localhost:5433/reagentes_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    repair: true
    validate-on-migrate: false

server:
  port: 8080

logging:
  level:
    com.reagentes: DEBUG
    org.springframework.web: DEBUG
    org.springframework.context: DEBUG

jwt:
  secret: ${JWT_SECRET:secret}
  issuer: ${JWT_ISSUER:project}
  expiration-time-in-days: ${JWT_EXPIRATION_TIME_IN_DAYS:7}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:8081,http://localhost:19000,http://localhost:19006}
