INSERT INTO materia (nome, created_at, updated_at) VALUES ('BPL', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('IAQ', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('TMI', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('SICO', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('APFQ I', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('APFQ II', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('AQL', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('AQT', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('OUPI', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('QP', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('AQA', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('AQI', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('MI', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('PDTCC', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('PE-Corrosão', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('PQI', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('QA', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('DOAÇÃO', NOW(), NOW());
INSERT INTO materia (nome, created_at, updated_at) VALUES ('COMPRA', NOW(), NOW());