CREATE TABLE IF NOT EXISTS reagentes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    quantidade DECIMAL(10,3) NOT NULL DEFAULT 0.000,
    unidade VARCHAR(10) NOT NULL DEFAULT 'g',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS materia (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS turmas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sala VARCHAR(20) NOT NULL,
    nome VARCHAR(10) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS movimentacoes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('ENTRADA', 'RETIRADA') NOT NULL,
    reagente_id BIGINT NOT NULL,
    quantidade DECIMAL(10,3) NOT NULL,
    materia_id BIGINT NOT NULL,
    turma_id BIGINT NOT NULL,
    data DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (reagente_id) REFERENCES reagentes(id),
    CONSTRAINT fk_movimentacoes_materia FOREIGN KEY (materia_id) REFERENCES materia(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_movimentacoes_turma FOREIGN KEY (turma_id) REFERENCES turmas(id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
