spring:
  application:
    name: reagentes-api

  datasource:
    url: jdbc:mysql://localhost:3306/reagentes_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    repair: true
    validate-on-migrate: false

server:
  port: 8080

logging:
  level:
    com.reagentes: DEBUG
    org.springframework.web: DEBUG
    org.springframework.context: DEBUG

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:project}
  expiration-time-in-days: ${JWT_EXPIRATION_TIME_IN_DAYS:7}
