INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Silicagel azul', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Acetato de amonio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Acetato de calcio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Acetato de etila', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Acetato de sódio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Acetato de zinco', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Acetona', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido fosfomolibidico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Acido acético glacial', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido benzóico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido Bórico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido cítrico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido Clorídrico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Acido Fênico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido L-ascorbico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido Nitrico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido salicilico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido sulfâmico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ácido sulfurico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Alcool etilico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Alcool Isopropilico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Alcool metilico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Alumen de potassio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Aluminio metalico em aparas', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Alumino metalico em pó', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Amido soluvel', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Anidro Cromico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Anilina', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Benzoato de sódio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Biftalato de potássio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Bióxido de manganes', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Bissulfito de Sódio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Borato de Sódio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Brometo de potássio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Brometo de sódio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Carbonato de Amonio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Carbonato de Calcio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Carbonato de potássio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Carbonato de sódio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Carbureto', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Carvão ativo em pó', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ciclohexano', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Citrato de sódio anidro', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Citrato de sódio tribasico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Clorato de potassio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloreto de aluminio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloreto de amonio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloreto de Bario', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloreto de estanho', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloreto de estrôncio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloreto de magnésio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloreto de mercurio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloreto de potassio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cloridrato de hidróxilamina', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cobre', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Cromato de Potássio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Diclorometano', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Dicromato de Amônio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Dicromato de Potássio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('EDTA', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Enxofre', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ferro', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Ferro em pó', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Fluoreto de sódio', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Fluoroglucina', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Fosfato de potássio mono.', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Fosfato sódio monobásico', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Hdróxido de Bario', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Hexano', 1.0, 'g');
INSERT INTO reagente (nome, quantidade, unidade) VALUES ('Hidróxido de Amônio', 1.0, 'g');
